#' @title Plot method for \pkg{svyEffects} objects
#' @name plot
#'
#' @description Uses the \pkg{ggplot2} engine to visualize the predicted
#' probabilities or differences in predicted probabilities calculated by
#' \pkg{svyEffects}.
#'
#' @param x An object of class \pkg{svyEffects} generated by the either of
#' the functions \code{svyAME} or \code{svyMER}.
#' @param what A string denoting whether predictions or differences should be
#' plotted. These are the dataframes \code{$preds} and \code{$diffs}, which are
#' contained within the output generated by either \code{svyAME} or \code{svyMER}.
#' @param ... Other arguments passed on the output.
#'
#' @importFrom ggplot2 ggplot aes labs theme_bw facet_wrap coord_flip geom_pointrange geom_line geom_ribbon
#' @importFrom scales percent
#' @importFrom rlang sym
#'
#' @return An object of class \code{ggplot}
#'
#' @author John Santos
#'
#' @export
#'
#'
#' @examples
#' data(ces19)
#' library(survey)
#' library(ggplot2)
#' ces19_svy <- svydesign(ids = ~1, strata = NULL, weights = ~pesweight,
#'   data = ces19, digits = 3)
#' VOTECON <- svyglm(votecon ~ agegrp + gender + educ + region + marketlib,
#'   design = ces19_svy, family = binomial)
#' ame_educ <- svyAME(VOTECON, varname = "educ", weightvar = "pesweight", seed = 2019)
#' plot(ame_educ)   # plots predicted probabilities
#' plot(ame_educ, "diffs")   # plots differences for pairwise comparisons
#'
#' # Plots can be customized using ggplot's conventions, e.g.:
#' plot(ame_educ) +
#'   geom_hline(yintercept = 0, linetype = "dotted")
#'   labs(title = "mytitle",
#'        x = "x axis label",
#'        y = "y axis label",
#'        caption = "my caption") +
#'  theme_classic() +
#'  theme(axis.text.x = element_text(angle=45, hjust=1))
#'
plot.svyEffects <- function(x,
                            what = c("preds", "diffs"),
                            ...) {

  # Setup ----------------------------------------------------------------------

  predvar <- attr(x, "predvar")
  depvar <- attr(x, "depvar")

  if(!is.null(attr(x, "byvar"))) {
    byvar <- attr(x, "byvar")
  }

  plotwhat <- match.arg(what)
  plotwhat <- switch(plotwhat,
                     NULL = "preds",
                     "preds" = "preds",
                     "diffs" = "diffs")

  # Main plot command ----------------------------------------------------------

  p <-
    ggplot2::ggplot(x[[plotwhat]]) +
    ggplot2::aes(x = !!sym(predvar),
        y = predicted,
        ymin = conf.low,
        ymax = conf.high) +
    ggplot2::labs(title = paste0("Mean predictions of ", depvar, " by ", predvar),
         y = paste0("Probability of ", depvar)) +
    ggplot2::theme_bw()

  ## If plotting ordinal/multinomial models ------------------------------------

  if("y" %in% colnames(x$preds)) {


    p <-
      p +
      facet_wrap(~y)
  }

  # If plotting DIFFS ----------------------------------------------------------

  if(plotwhat=="diffs") {
    p <-
      p +
      ggplot2::geom_pointrange() +
      ggplot2::labs(title = paste0("Mean predictions of ", depvar, " by ", predvar),
           y = paste0("Difference in probability of ", depvar),
           x = "Contrast") +
      ggplot2::coord_flip()
  }

  # If plotting PREDS ----------------------------------------------------------

  if(plotwhat=="preds") {

    ## Univariate model geoms --------------------------------------------------

    if(is.null(attr(x, "byvar"))) {

      if(is.factor(x$preds[[predvar]])) {
        p <-
          p +
          ggplot2::geom_pointrange()
      }

      if(is.numeric(x$preds[[predvar]])) {
        p <-
          p +
          ggplot2::geom_line() +
          ggplot2::geom_ribbon(colour="transparent", alpha=.2)
      }

    }

    ## Interactive model geoms -------------------------------------------------

    if(!is.null(attr(x, "byvar"))) {

      if(is.factor(x$preds[[predvar]])) {
        p <-
          p +
          ggplot2::geom_pointrange(position = position_dodge2(.35)) +
          ggplot2::aes(colour = !!sym(byvar))
      }

      if(is.numeric(x$preds[[predvar]])) {
        p <-
          p +
          aes(colour = !!sym(byvar), fill = !!sym(byvar)) +
          ggplot2::geom_line() +
          ggplot2::geom_ribbon(colour="transparent", alpha=.2)
      }
    }

  }

  # Output ---------------------------------------------------------------------

  return(p)

}
