#' @title Generic plot method for \pkg{svyEffects} objects
#' @name plot
#'
#' @description Uses the \pkg{ggplot2} engine to visualize the predicted
#' probabilities or differences in predicted probabilities calculated by
#' \pkg{svyEffects}.
#'
#' @param x An object of class \pkg{svyEffects} generated by the either of
#' the functions \code{svyAME} or \code{svyMER}.
#' @param what A string denoting whether predictions or differences should be
#' plotted. These are the dataframes \code{$preds} and \code{$diffs}, which are
#' contained within the output generated by either \code{svyAME} or \code{svyMER}.
#' @param ... Other arguments passed on the output.
#'
#' @importFrom ggplot2 ggplot
#' @importFrom scales percent
#' @importFrom rlang sym
#'
#' @return An object of class \code{ggplot}
#' @export
#'
plot.svyEffects <- function(x,
                            what = c("preds", "diffs"),
                            ...) {

  #---------- Setup ------------------------------------------------------------

  predvar <- attr(x, "predvar")
  depvar <- attr(x, "depvar")

  plotwhat <- match.arg(what)
  plotwhat <- switch(plotwhat,
                     NULL = "preds",
                     "preds" = "preds",
                     "diffs" = "diffs")

  #---------- Main plot command ------------------------------------------------

  p <-
    ggplot(x[[plotwhat]]) +
    aes(x = !!sym(predvar),
        y = predicted,
        ymin = conf.low,
        ymax = conf.high) +
    labs(title = paste0("Mean predictions of ", depvar, " by ", predvar),
         y = paste0("Probability of ", depvar)) +
    theme_bw()

  #---------- Add geoms by variable type ---------------------------------------

  if(is.factor(x$preds[[predvar]])) {
    p <-
      p +
      geom_pointrange()
  }

  if(is.numeric(x$preds[[predvar]])) {
    p <-
      p +
      geom_line() +
      geom_ribbon(colour="transparent", alpha=.2)
  }

  #---------- If plotting differences ------------------------------------------

  if(plotwhat=="diffs") {
    p <-
      p +
      geom_pointrange() +
      labs(title = paste0("Mean predictions of ", depvar, " by ", predvar),
           y = paste0("Difference in probability of ", depvar),
           x = "Contrast") +
      coord_flip()
  }

  #---------- If plotting ordinal/multinomial models

  if("y" %in% colnames(x$preds)) {
    p <-
      p +
      facet_wrap(~y)
  }

  #---------- Output -----------------------------------------------------------

  return(p)

}
