#' @title Print method for \pkg{svyEffects} objects
#' @name print
#'
#' @description Prints results for \code{svyEffects} of objects
#'
#' @param x An object of class \pkg{svyEffects} generated by the either of
#' the functions \code{svyAME} or \code{svyMER}.
#' @para digits = Scalar
#' @param ... Other arguments passed on the output.
#'
#' @importFrom dplyr arrange as_tibble filter group_by mutate mutate_if rename relocate select summarize tibble
#' @importFrom glue glue
#' @importFrom magrittr %>%
#' @importFrom rlang sym
#'
#' @return A dataframe
#'
#' @author John Santos
#'
#' @export
#'
#'
#' @examples
#'
print.svyEffects <- function(x, nrow = 40, digits = 3, ...) {

  print(glue("Dependent variable: ", attr(x, "depvar")))
  print(glue("Predictor variable: ", attr(x, "predvar")))
  if("depvar" %in% names(attributes(x))) {
    print(glue("Moderator variable: ", attr(x, "byvar")))
    print(glue("
             "))
  }
  print(glue("Seed value: ", m1_reg_ame$seed))
  print(glue("Number of simulations: ", m1_reg_ame$sims))
  print(glue("

             "))
  print(glue("Predicted probabilities: "))
  x$preds %>%
    dplyr::mutate_if(is.numeric, round, digits = digits) %>%
    print(n = nrow)
  print(glue("

             "))
  if(!is.null(x$diffs)) {
    print(glue("Differences in predicted probabilities: "))
    x$diffs %>%
      mutate_if(is.numeric, round, digits = digits) %>%
      print(n = nrow)
  }
}

